/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.kotlin.tables.references


import org.jooq.mcve.kotlin.tables.MyTable



/**
 * The table <code>mcve.my_table</code>.
 */
val MY_TABLE = MyTable.MY_TABLE
