/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.kotlin


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.UDT
import org.jooq.impl.SchemaImpl
import org.jooq.mcve.kotlin.tables.MyTable
import org.jooq.mcve.kotlin.udt.MyUdt


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Mcve : SchemaImpl("mcve", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>mcve</code>
         */
        val MCVE = Mcve()
    }

    /**
     * The table <code>mcve.my_table</code>.
     */
    val MY_TABLE get() = MyTable.MY_TABLE

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        MyTable.MY_TABLE
    )

    override fun getUDTs(): List<UDT<*>> = listOf(
        MyUdt.MY_UDT
    )
}
