/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.scala


import org.jooq.mcve.scala.tables.MyTable


/**
 * Convenience access to all tables in mcve.
 */
object Tables {

  /**
   * The table <code>mcve.my_table</code>.
   */
  lazy val MY_TABLE = MyTable.MY_TABLE
}
