/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java;


import org.jooq.mcve.java.tables.MyTable;


/**
 * Convenience access to all tables in mcve.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mcve.my_table</code>.
     */
    public static final MyTable MY_TABLE = MyTable.MY_TABLE;
}
